# Spring的配置,可以配置到nacos中,使用nacos来管理
spring:
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db-type: mysql
      url: jdbc:p6spy:mysql://192.168.56.101:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false
      username: britton
      password: britton
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
      async-init: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 60000
      validation-query-timeout: 30
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123

# Mybatis Plus的配置,可以配置到nacos中,使用nacos来管理
mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.geoxus
  type-enums-package: com.geoxus
  type-handlers-package: com.geoxus
  global-config:
    db-config:
      id-type: auto
      capital-mode: true
      logic-delete-field: is_delete
      logic-delete-value: 0
      logic-not-delete-value: 1
      column-format: "%s"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true

# dubbo的配置,可以配置到nacos中,使用nacos来管理
dubbo:
  registry:
    address: nacos://192.168.1.103:8848
    parameters: { namespace: d937e439-cac3-4004-8f13-b88fbe0bcd56, group: GX_GROUP, id: provider }
  scan:
    base-packages: com.geoxus.service
  application:
    name: provider-dubbo-provider
  protocols:
    dubbo:
      name: dubbo
      port: 8090
      server: netty
  consumer:
    timeout: 5000
    check: false
    retries: 0
  provider:
    timeout: 5000
    retries: 0
# 以下关于nacos的配置信息必须配置到application.yml文件中 , 以上信息可以配置到nacos中 , 使用nacos来管理
nacos:
  config:
    server-addr: 127.0.0.1:8848
    auto-refresh: true
    bootstrap:
      enable: true  # 需要配置data-id 和 type  否则会报错
    data-id: britton.test.yml
    type: yaml
    namespace: d937e439-cac3-4004-8f13-b88fbe0bcd56  # 需要设置  否则不能自动更新

