server:
  port: 3030
  servlet:
    context-path: /consumer

spring:
  application:
    name: consumer
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db-type: mysql
      url: jdbc:p6spy:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false
      username: britton
      password: britton
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
      async-init: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 60000
      validation-query-timeout: 30
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.geoxus
  type-enums-package: com.geoxus
  type-handlers-package: com.geoxus
  global-config:
    db-config:
      id-type: auto
      capital-mode: true
      logic-delete-field: is_delete
      logic-delete-value: 0
      logic-not-delete-value: 1
      column-format: "%s"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    parameters: { namespace: 254cd78f-885d-4f05-b88d-bee895b7f0e9 }
  scan:
    base-packages: com.geoxus.service
  protocol:
    name: dubbo
  application:
    name: consumer-dubbo-consumer