server:
  port: 4040
  servlet:
    context-path: /provider

spring:
  application:
    name: provider

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    parameters: { namespace: 254cd78f-885d-4f05-b88d-bee895b7f0e9 }
  scan:
    base-packages: com.geoxus.service
  protocol:
    name: dubbo
    port: 15511
  application:
    name: provider-dubbo-provider

nacos:
  config:
    server-addr: 127.0.0.1:8848
    auto-refresh: true
    bootstrap:
      enable: true  # 需要配置data-id 和 type  否则会报错
    data-id: britton.test.yml
    type: yaml
    namespace: 254cd78f-885d-4f05-b88d-bee895b7f0e9  # 需要设置  否则不能自动更新

